name: Create Release

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
  #push:
  #  tags:
  #    - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_phone_and_wear_app:
    name: "Build app"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Release Apk
        run: ./gradlew assembleRelease

      - name: Sign phone Apk
        uses: r0adkll/sign-android-release@v1
        id: sign_phone_apk
        with:
          releaseDirectory: phone/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Generate Release bundles
        run: ./gradlew bundleRelease

      - name: Sign phone bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_phone_bundle
        with:
          releaseDirectory: phone/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Sign wear bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_wear_bundle
        with:
          releaseDirectory: wear/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Create github release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ github.ref_name }}
          files: |
            ${{steps.sign_phone_apk.outputs.signedReleaseFile}}
            ${{steps.sign_phone_bundle.outputs.signedReleaseFile}}
            ${{steps.sign_wear_bundle.outputs.signedReleaseFile}}
